[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.curl", "php83Extensions.mbstring", "php83Extensions.pdo"]

[phases.build]
cmds = ["echo 'No build needed'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public public/router.php"
